image: node:10

stages:
  - build
  - finish

build:
  stage: 'build'
  script:
    - apt update
    - apt install -y curl
    - apt install -y nodejs
    - npm install -y npm@latest -g
    - npm install -g @angular/cli
    - cd /builds/ADogan/verkeertrainer/client
    - rm package-lock.json
    - npm install
    - ng build --prod
  cache: 
    paths: 
      - /builds/ADogan/verkeertrainer/client/node_modules/
  artifacts:
      when: on_success
      name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
      paths:
        - /builds/ADogan/verkeertrainer/client/dist/

finish:
  stage: 'finish'
  script:
    - pwd
    - ls -all
    - echo $FB_SECRET
