image: node:10

stages:
  - build

build:
  stage: 'build'
  script:
    - apt update
    - apt install -y curl
    - apt install -y nodejs
    - npm install -y npm@latest -g
    - npm install -g @angular/cli
    - cd /builds/ADogan/verkeertrainer
    - rm package-lock.json
    - npm install
    - cd ..
    - ng build --prod