image: node:10

stages:
  - build
  - test
  - deploy

build:
  stage: 'build'
  script:
    - apt update
    - apt install -y curl
    - apt install -y nodejs
    - npm install -y npm@latest -g
    - npm install -g @angular/cli
    - cd /builds/ADogan/verkeertrainer/web
    - rm package-lock.json
    - npm install
    - ng build --prod
  cache:
    paths:
      - /builds/ADogan/verkeertrainer/web/node_modules/
  artifacts:
      when: on_success
      name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
      paths:
        - /builds/ADogan/verkeertrainer/web/dist/

test:
  stage: 'test'
  script:
    - echo 'unit tests and e2e tests'

deploy:
  stage: 'deploy'
  script:
    - npm install -g firebase-tools
    - cd /builds/ADogan/verkeertrainer/
    - firebase -V
    - firebase deploy --token "1/$FB_TKN" -P "$FB_PROJECTNAME"
  only:
    - master
